# Theme configuration
name: 'Example Theme'
description: 'This serves to illustrate the basic contents of a theme package.'
data_files: [
  units: 'units.json',
  weapons: 'weapons.json',
  factions: 'factions.json',
  modifiers: 'mods.json',
]